require('should');

const zapier = require('zapier-platform-core');

const App = require('../index');
const appTester = zapier.createAppTester(App);

describe('oauth2 app', () => {
  before(() => {
    // It's a good idea to store your Client ID and Secret in the environment rather than in code.
    // This works locally via the `export` shell command and in production by using `zapier env`
    if (!process.env.CLIENT_ID) {
      throw new Error('For the tests to run, you need to do `export CLIENT_ID=1234`');
    }
  });

  it('generates an authorize URL', () => {
    const bundle = {
      // In production, these will be generated by Zapier and set automatically
      inputData: {
        state: '4444',
        redirect_uri: 'http://zapier.com/'
      },
      environment: {
        CLIENT_ID: process.env.CLIENT_ID,
      }
    };

    return appTester(App.authentication.oauth2Config.authorizeUrl, bundle)
      .then((authorizeUrl) => {
        authorizeUrl.should.eql(`https://memair.com/oauth/authorize?client_id=${bundle.environment.CLIENT_ID}&redirect_uri=http%3A%2F%2Fzapier.com%2F&response_type=code`);
      });
  });
});
